FROM node:12.18.3-alpine
LABEL maintainer="michael <micjoyce90@gmail.com>"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk update \
    && apk add --no-cache imagemagick-dev imagemagick ghostscript \
    && apk add libreoffice

ENV LANG en_GB.UTF-8
RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family font-isas-misc && rm -rf /var/cache/apk/*

COPY ./resource/simhei.ttf /usr/share/fonts/simhei.ttf

RUN mkdir -p /app
WORKDIR /app

COPY ./package* /app/
RUN npm config set registry http://registry.npm.taobao.org/
RUN npm install

COPY . /app

ENV PORT=3000

EXPOSE 3000
CMD [ "npm", "run", "dev" ]

